HTTP GET instead of POST
I get this on client!
```    answer = requests.post(url=sel_url.format(), json=params)
  File
"/usr/lib/python3/dist-packages/two1/lib/bitrequests/bitrequests.py",
line 147, in post
    return self.request('post', url, max_price, **kwargs)
  File
"/usr/lib/python3/dist-packages/two1/lib/bitrequests/bitrequests.py",
line 129, in request
    raise ValueError(paid_response.json()["detail"])
KeyError: 'detail’```